# Playing with numPy
## Visit https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
### import numpy, see the version

In [2]:
import numpy as np
np.version.version

'1.9.2'

## First steps: creating vectors and matrices: 'ndarrys'. 
### create ndarrays from a list, from list of list. See dim, shape, reshape.

In [8]:
b = np.array([1,2,3,4])
b = np.array([[11,12,13],[21,22,23],[31,32,33]])
print b
# Shape, reshape and dim : http://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r
b.shape


[[11 12 13]
 [21 22 23]
 [31 32 33]]


(3, 3)

### special ndarrays: zeros, ones, ones_like, eye, empty.

### arange and random

## Indexing and slicing
### (1) Acessing narrays

### (2) Slicing

### (3) Copying: careful!!

## Basic operations
### (1) Element wise operations

### (2) Operations on matrixes: dot, transpose, sum, cumsum, cumprod...

## numPy ndarrays versus matrix

## Linear Algebra
### See http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html

In [2]:
from numpy import linalg as la

In [3]:
help(la)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

FILE
    /Users/juarele/anaconda/lib/python2.7/site-packages/numpy/linalg/__init__.py

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr       

### Trace, determinant and inverse

### Norm of a vector and a matrix

In [4]:
help(la.norm)

Help on function norm in module numpy.linalg.linalg:

norm(x, ord=None, axis=None)
    Matrix or vector norm.
    
    This function is able to return one of seven different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D.
    ord : {non-zero int, inf, -inf, 'fro'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object.
    axis : {int, 2-tuple of ints, None}, optional
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these matrices
        are computed.  If `axis` is None then either a vector norm (when `x`
        is 1-D) or a matrix norm (when `x` is 2-D) is returned.
    

### Matrix factorization: eigen-decomposition y SVD

### Comparison with python: execution times 

In [5]:
import time
size_of_vec = 1000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

In [6]:
t1 = pure_python_version()
t2 = numpy_version()
print(t1/t2)

8.86092715232
