# Playing with numPy
## Visit https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

In [1]:
import numpy as np

In [2]:
%%bash
which python

/Users/juarele/anaconda/bin/python


In [3]:
np.version.version

'1.9.2'

## First steps: creating vectors and matrices: 'ndarrys'. 

In [4]:
list = [1, 2.0,3.1,4.2,-1,8.92]

In [5]:
a = np.array(list)
a.dtype

dtype('float64')

In [6]:
a.shape

(6,)

In [7]:
a.ndim

1

In [8]:
np.array( [ [1,2], [3,4] ], dtype=complex )

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [9]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print a2

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [50]:
print a.shape, a2.shape
print a.size,a2.size

(6,) (4, 3)
6 12


In [11]:
print np.zeros(10)
print np.ones((2,3))
print np.ones_like(a2)
print np.eye(4)
print np.empty((2,3,2))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[[  4.94065646e-324   4.94065646e-324]
  [  4.94065646e-324   4.94065646e-324]
  [  4.94065646e-324   4.94065646e-324]]

 [[  4.94065646e-324   4.94065646e-324]
  [  4.94065646e-324   4.94065646e-324]
  [  4.94065646e-324   4.94065646e-324]]]


In [12]:
print np.arange(10)
print np.arange( 10, 30, 5 )
print np.arange( 0, 2, 0.3 )

[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]


In [13]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [14]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ..., 
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [15]:
np.random.random((2,3))

array([[ 0.20994276,  0.33294225,  0.25077248],
       [ 0.96196943,  0.37252138,  0.875393  ]])

## Indexing and slicing
### (1) Acessing narrays

In [16]:
print a
print a2

[ 1.    2.    3.1   4.2  -1.    8.92]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
print a[0],a2[0]

1.0 [1 2 3]


In [18]:
a2[1][0] 

4

In [19]:
a2[1,0]

4

### (2) Slicing

In [20]:
a[1:3]

array([ 2. ,  3.1])

In [21]:
a2[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
a2[:2,:2]

array([[1, 2],
       [4, 5]])

In [23]:
a2 >3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [121]:
print a2[a2==3]
print a2[a2>3]
print a2[a2 %2 == 0]

[3 3 3 3]
[ 7  8  9 10 11 12]
[ 2  8 10 12]


### (3) Copying: careful!!

In [25]:
b=a2[1]

In [26]:
b[1]=-1

In [27]:
a2

array([[ 1,  2,  3],
       [ 4, -1,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
b[:]=3

In [29]:
a2 

array([[ 1,  2,  3],
       [ 3,  3,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
c=a2[1].copy()
c

array([3, 3, 3])

In [31]:
c[:]=[1,-3,0]

In [32]:
print c
print a2

[ 1 -3  0]
[[ 1  2  3]
 [ 3  3  3]
 [ 7  8  9]
 [10 11 12]]


## Basic operations
### (1) Element wise operations

In [33]:
print a2
a2*a2 

[[ 1  2  3]
 [ 3  3  3]
 [ 7  8  9]
 [10 11 12]]


array([[  1,   4,   9],
       [  9,   9,   9],
       [ 49,  64,  81],
       [100, 121, 144]])

In [34]:
a2 -a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
1/a2

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
a2**2

array([[  1,   4,   9],
       [  9,   9,   9],
       [ 49,  64,  81],
       [100, 121, 144]])

In [37]:
np.sin(a2)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001,  0.14112001,  0.14112001],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])

### (2) Operations on matrixes

In [38]:
a.dot(a)

112.8164

In [39]:
a2.dot(np.arange(3))

array([ 8,  9, 26, 35])

In [40]:
a2.transpose()

array([[ 1,  3,  7, 10],
       [ 2,  3,  8, 11],
       [ 3,  3,  9, 12]])

In [41]:
a2.transpose((1,0))

array([[ 1,  3,  7, 10],
       [ 2,  3,  8, 11],
       [ 3,  3,  9, 12]])

In [42]:
np.ones((4,3,2)).transpose((2,1,0)).shape

(2, 3, 4)

In [43]:
print a2.sum()
print a2.cumsum()
print a2.cumprod()

72
[ 1  3  6  9 12 15 22 30 39 49 60 72]
[        1         2         6        18        54       162      1134
      9072     81648    816480   8981280 107775360]


## numPy ndarrays versus matrix

In [44]:
a3 = np.mat(a2)
a3

matrix([[ 1,  2,  3],
        [ 3,  3,  3],
        [ 7,  8,  9],
        [10, 11, 12]])

In [45]:
a3.T

matrix([[ 1,  3,  7, 10],
        [ 2,  3,  8, 11],
        [ 3,  3,  9, 12]])

In [46]:
a3.T*a3

matrix([[159, 177, 195],
        [177, 198, 219],
        [195, 219, 243]])

In [47]:
a3[:2,:2].I

matrix([[-1.        ,  0.66666667],
        [ 1.        , -0.33333333]])

In [48]:
a3[:2,:2].I*a3[:2,:2]

matrix([[ 1.,  0.],
        [ 0.,  1.]])

## Linear Algebra
### See http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html

In [49]:
from numpy import linalg as la

In [52]:
help(la)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

FILE
    /Users/juarele/anaconda/lib/python2.7/site-packages/numpy/linalg/__init__.py

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr       

### Trace, determinant and inverse

In [57]:
np.trace(np.eye(3))

3.0

In [61]:
print a2
print np.trace(a2)
print np.trace(a2,offset=1)
print np.trace(a2,offset=-1)

[[ 1  2  3]
 [ 3  3  3]
 [ 7  8  9]
 [10 11 12]]
13
5
23


In [70]:
a = np.array([[1, 2], [3, 4]])
print a
print a.shape
la.det(a)

[[1 2]
 [3 4]]
(2, 2)


-2.0000000000000004

In [69]:
a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [2, 1]],

       [[1, 3],
        [3, 1]]])

In [68]:
print a.shape
print la.det(a)

(3, 2, 2)
[-2. -3. -8.]


In [71]:
la.inv(np.array([[1,2],[3,4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [72]:
la.inv(np.array([[1,2],[3,4]])).dot(np.array([[1,2],[3,4]]))

array([[  1.00000000e+00,   0.00000000e+00],
       [  2.22044605e-16,   1.00000000e+00]])

### Norm of a vector and a matrix

In [76]:
a = np.array([[1, 2], [3, 4]])
help(la.norm)

Help on function norm in module numpy.linalg.linalg:

norm(x, ord=None, axis=None)
    Matrix or vector norm.
    
    This function is able to return one of seven different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D.
    ord : {non-zero int, inf, -inf, 'fro'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object.
    axis : {int, 2-tuple of ints, None}, optional
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these matrices
        are computed.  If `axis` is None then either a vector norm (when `x`
        is 1-D) or a matrix norm (when `x` is 2-D) is returned.
    

In [89]:
print a
print la.norm(a)
print la.norm(a,2)
print la.norm(a,'fro')
print la.norm(a.reshape(4),2)
print la.norm(a,1)
print la.norm(a,np.inf)


[[1 2]
 [3 4]]
5.47722557505
5.46498570422
5.47722557505
5.47722557505
6
7


In [92]:
b = np.arange(1,4)
print b
print la.norm(b)
print la.norm(b,2)
print la.norm(b,1)
print la.norm(b,np.inf)


[1 2 3]
3.74165738677
3.74165738677
6
3


### Matrix factorization: eigen-decomposition y SVD

In [101]:
eigval = la.eigvals(a)
eigval

array([-0.37228132,  5.37228132])

In [102]:
eigvec = la.eig(a)[1]
eigvec

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [103]:
eigvec.dot(np.diag(eigval)).dot(la.inv(eigvec))

array([[ 1.,  2.],
       [ 3.,  4.]])

In [107]:
u, d,v = la.svd(a)
print u
print d
print v

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[ 5.4649857   0.36596619]
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [109]:
u.dot(np.diag(d)).dot(v)

array([[ 1.,  2.],
       [ 3.,  4.]])

In [112]:
b = np.array([b,b])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [115]:
u,d,v=la.svd(b)
print u
print d
print v

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[  5.29150262e+00   4.44089210e-16]
[[-0.26726124 -0.53452248 -0.80178373]
 [ 0.94491118 -0.30854944 -0.10927077]
 [-0.18898224 -0.78681825  0.58753958]]


In [116]:
u,d,v=la.svd(b,full_matrices=0)
print u
print d
print v

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[  5.29150262e+00   4.44089210e-16]
[[-0.26726124 -0.53452248 -0.80178373]
 [ 0.94491118 -0.30854944 -0.10927077]]


In [126]:
u,d,v = la.svd(np.random.rand(1000,4))
u2,d2,v2 = la.svd(np.random.rand(1000,4),full_matrices=0)
print u.shape,d.size,v.shape
print u2.shape,d2.size,v2.shape

(1000, 1000) 4 (4, 4)
(1000, 4) 4 (4, 4)


### Comparison with python: execution times 

In [117]:
import time
size_of_vec = 1000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

In [119]:
t1 = pure_python_version()
t2 = numpy_version()
print(t1/t2)

12.7686567164
